# SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
# Copyright (c) 2026 Wireless System Research Group, McMaster University

"""RT/PO simulation engines, coupling, blockage, and profiling helpers."""

from importlib import import_module


# Importing a lightweight submodule such as ``motion_diagnostics`` should not
# initialize Mitsuba, Sionna, every simulation engine, and Matplotlib. Public
# names remain available from this package and are loaded on first access.
_EXPORT_MODULES = {
    "numpy_dtypes_for_precision": "adc_synthesis",
    "synthesize_adc_from_paths": "adc_synthesis",
    "EnvHumanCouplingResult": "env_human_coupling",
    "EnvironmentReflectorBank": "env_human_coupling",
    "compute_env_human_coupling_channels": "env_human_coupling",
    "extract_environment_reflector_bank": "env_human_coupling",
    "extract_rt_reflector_bank": "env_human_coupling",
    "CalibratedHybridPOResult": "hybrid_pipeline",
    "FullRTMobilityBaselineResult": "hybrid_pipeline",
    "RTMobilityBaselineResult": "hybrid_pipeline",
    "HybridCouplingRecomputeResult": "hybrid_pipeline",
    "hybrid_rt_path_coupling": "hybrid_pipeline",
    "recompute_hybrid_rt_path_coupling": "hybrid_pipeline",
    "run_calibrated_hybrid_po": "hybrid_pipeline",
    "run_full_scene_rt_comparison": "hybrid_pipeline",
    "run_full_rt_mobility_baseline": "hybrid_pipeline",
    "run_rt_mobility_baseline": "hybrid_pipeline",
    "run_hybrid_rt_path_pipeline": "hybrid_pipeline",
    "ComputeBackend": "physical_optics",
    "ComputePrecision": "physical_optics",
    "FaceVisibilityState": "physical_optics",
    "HumanVisibilityScene": "physical_optics",
    "POChannelResult": "physical_optics",
    "POIntegrationMode": "physical_optics",
    "PhysicalOpticsMaterial": "physical_optics",
    "face_geometry": "physical_optics",
    "parent_face_far_field_analytic_geometry": "physical_optics",
    "parent_face_far_field_edge_rule": "physical_optics",
    "parent_face_quadrature_geometry": "physical_optics",
    "po_channel": "physical_optics",
    "vector_facet_channel": "physical_optics",
    "vector_facet_face_contributions": "physical_optics",
    "PointTarget": "point_targets",
    "PointTargetSynthesisResult": "point_targets",
    "azimuth_elevation_axes": "point_targets",
    "azimuth_elevation_grids": "point_targets",
    "calibrate_range_cube_channel_phase": "point_targets",
    "db_relative": "point_targets",
    "make_point_target_fmcw_config": "point_targets",
    "range_resolved_angle_fft": "point_targets",
    "synthesize_virtual_center_point_targets": "point_targets",
    "target_direction_cosines": "point_targets",
    "virtual_snapshot_grid": "point_targets",
    "POIncrementalProfileResult": "po_profile",
    "POIncrementalSweepSetting": "po_profile",
    "cube_matches_run": "po_profile",
    "flatten_adc_for_fft": "po_profile",
    "label_slug": "po_profile",
    "load_radar_cube_npz": "po_profile",
    "make_incremental_po_config": "po_profile",
    "range_profiles_for_cube": "po_profile",
    "relative_norm_error": "po_profile",
    "run_incremental_po_sweep": "po_profile",
    "save_radar_cube_npz": "po_profile",
    "summarize_incremental_po_result": "po_profile",
    "CoherentRTPathBank": "rt_coherence",
    "CoherentRTPathTransition": "rt_coherence",
    "CoherentRTPathUpdate": "rt_coherence",
    "CoherentRTTransitionSynthesis": "rt_coherence",
    "barycentric_coordinates": "rt_coherence",
    "coherent_transition_weights": "rt_coherence",
    "extract_coherent_rt_path_bank": "rt_coherence",
    "match_coherent_rt_path_banks": "rt_coherence",
    "synthesize_coherent_rt_transition": "rt_coherence",
    "update_coherent_rt_path_bank": "rt_coherence",
    "configure_mitsuba_variant": "runtime",
    "runtime_summary": "runtime",
    "select_torch_device": "runtime",
    "torch_runtime_summary": "runtime",
    "RTPilotSelection": "rt_schedule_profile",
    "RTFixedScheduleCurveProfile": "rt_schedule_profile",
    "RTScheduleCostPoint": "rt_schedule_profile",
    "RTTransitionMetrics": "rt_schedule_profile",
    "normalize_retrace_schedule_indices": "rt_schedule_profile",
    "periodic_retrace_schedule_indices": "rt_schedule_profile",
    "profile_fixed_retrace_scheme_curves": "rt_schedule_profile",
    "profile_transition_metrics": "rt_schedule_profile",
    "recommend_periodic_retrace_period": "rt_schedule_profile",
    "rt_profile_trace_budget": "rt_schedule_profile",
    "select_budgeted_pilot_indices": "rt_schedule_profile",
    "transition_metrics_for_pair": "rt_schedule_profile",
    "POCalibrationConfig": "calibration",
    "calibration_gain_array": "calibration",
    "fit_sequence_path_power_calibration": "calibration",
    "RadialVelocitySamples": "motion_diagnostics",
    "equivalent_bistatic_radial_velocity": "motion_diagnostics",
    "mesh_sequence_radial_velocity_samples": "motion_diagnostics",
    "radial_velocity_summary": "motion_diagnostics",
    "HybridStaticEnvPOConfig": "types",
    "HumanPOMobilityConfig": "types",
    "RTCoherentTransitionConfig": "types",
    "RadarCube": "types",
    "SENSING_METADATA_SCHEMA_VERSION": "types",
    "SensingMetadata": "types",
    "MmWaveRadarSimulator": "simulator",
    "PathVisibilityState": "static_blocking",
    "StaticPathBank": "static_blocking",
    "blocked_path_visibility": "static_blocking",
    "extract_static_path_bank": "static_blocking",
    "segment_indices_intersecting_aabb": "static_blocking",
    "synthesize_blocked_static_cube": "static_blocking",
    "update_path_visibility_state": "static_blocking",
}


def __getattr__(name: str):
    """Loads one public simulation symbol on first use."""

    module_name = _EXPORT_MODULES.get(name)
    if module_name is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    value = getattr(import_module(f".{module_name}", __name__), name)
    globals()[name] = value
    return value


def __dir__() -> list[str]:
    """Includes lazy public names in interactive discovery."""

    return sorted((*globals(), *__all__))

__all__ = [
    "ComputeBackend",
    "ComputePrecision",
    "CoherentRTPathBank",
    "CoherentRTPathTransition",
    "CoherentRTPathUpdate",
    "CoherentRTTransitionSynthesis",
    "EnvHumanCouplingResult",
    "EnvironmentReflectorBank",
    "FaceVisibilityState",
    "CalibratedHybridPOResult",
    "FullRTMobilityBaselineResult",
    "RTMobilityBaselineResult",
    "HumanPOMobilityConfig",
    "HumanVisibilityScene",
    "HybridCouplingRecomputeResult",
    "HybridStaticEnvPOConfig",
    "MmWaveRadarSimulator",
    "POCalibrationConfig",
    "calibration_gain_array",
    "POChannelResult",
    "POIntegrationMode",
    "POIncrementalProfileResult",
    "POIncrementalSweepSetting",
    "PathVisibilityState",
    "PhysicalOpticsMaterial",
    "PointTarget",
    "PointTargetSynthesisResult",
    "azimuth_elevation_axes",
    "azimuth_elevation_grids",
    "RadarCube",
    "RTCoherentTransitionConfig",
    "RadialVelocitySamples",
    "SENSING_METADATA_SCHEMA_VERSION",
    "SensingMetadata",
    "StaticPathBank",
    "barycentric_coordinates",
    "calibrate_range_cube_channel_phase",
    "coherent_transition_weights",
    "db_relative",
    "blocked_path_visibility",
    "compute_env_human_coupling_channels",
    "configure_mitsuba_variant",
    "cube_matches_run",
    "extract_environment_reflector_bank",
    "extract_rt_reflector_bank",
    "equivalent_bistatic_radial_velocity",
    "extract_static_path_bank",
    "extract_coherent_rt_path_bank",
    "match_coherent_rt_path_banks",
    "face_geometry",
    "fit_sequence_path_power_calibration",
    "parent_face_far_field_analytic_geometry",
    "parent_face_far_field_edge_rule",
    "parent_face_quadrature_geometry",
    "flatten_adc_for_fft",
    "hybrid_rt_path_coupling",
    "label_slug",
    "load_radar_cube_npz",
    "make_incremental_po_config",
    "make_point_target_fmcw_config",
    "mesh_sequence_radial_velocity_samples",
    "po_channel",
    "synthesize_coherent_rt_transition",
    "radial_velocity_summary",
    "range_profiles_for_cube",
    "range_resolved_angle_fft",
    "relative_norm_error",
    "recompute_hybrid_rt_path_coupling",
    "run_calibrated_hybrid_po",
    "run_full_scene_rt_comparison",
    "run_full_rt_mobility_baseline",
    "run_rt_mobility_baseline",
    "run_hybrid_rt_path_pipeline",
    "run_incremental_po_sweep",
    "normalize_retrace_schedule_indices",
    "periodic_retrace_schedule_indices",
    "RTFixedScheduleCurveProfile",
    "RTPilotSelection",
    "RTScheduleCostPoint",
    "RTTransitionMetrics",
    "profile_fixed_retrace_scheme_curves",
    "profile_transition_metrics",
    "recommend_periodic_retrace_period",
    "rt_profile_trace_budget",
    "select_budgeted_pilot_indices",
    "transition_metrics_for_pair",
    "runtime_summary",
    "select_torch_device",
    "torch_runtime_summary",
    "save_radar_cube_npz",
    "segment_indices_intersecting_aabb",
    "summarize_incremental_po_result",
    "synthesize_blocked_static_cube",
    "update_path_visibility_state",
    "update_coherent_rt_path_bank",
    "synthesize_virtual_center_point_targets",
    "target_direction_cosines",
    "numpy_dtypes_for_precision",
    "synthesize_adc_from_paths",
    "vector_facet_channel",
    "vector_facet_face_contributions",
    "virtual_snapshot_grid",
]
